### PR TITLE
JEN-971

### PR DESCRIPTION
**Pull request by abychko**
Jenkins cannot parse MTR test results properly after 5.7.24 upstream merge
[+] added regexp to filter lines related to tests

### CODE REVIEW

**Comment by abychko** [comment]
started test https://ps2.cd.percona.com/view/TEST/job/test-percona-server-5.7-pipeline/2/console

**Comment by laurynas-biveinis** [comment]
Please notify once the test completes

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Please replace copy-pasting with a e.g. a bash function, like in 8.0

**Comment by abychko** [comment]
fixed my commit, new test run https://ps2.cd.percona.com/view/TEST/job/test-percona-server-5.7-pipeline/3/console

**Comment by abychko** [comment]
properly fixed & tested https://ps2.cd.percona.com/view/TEST/job/test-percona-server-5.7-pipeline/10/

**Comment by abychko** [comment]
fixed calculation 
https://ps2.cd.percona.com/view/TEST/job/test-percona-server-5.7-pipeline/11/

**Comment by laurynas-biveinis** [comment]
Please ping here once test completes, code looks OK

**Pull request merged**
