### PR TITLE
8.0: switch to -DWITH_SYSTEM_LIBS=ON

### PR DESCRIPTION
**Pull request by abychko**
[-] deleted every occurence of WITH_SSL from Jenkins GUI and pipeline
    [-] replaced WITH_SSL with WITH_SYSTEM=libs in build scripts
    [-] deleted WITH_ZLIB
    [+] added liblz4 dev package to ubuntu/debian and centos
    [+] added libevent dev package to ubuntu/debian and centos
    [+] added libre2 dev package to ubuntu/debian and centos
    [+] added libicu dev package to ubuntu/debian and centos
    [+] added rapidjson dev package to ubuntu/debian and centos

### CODE REVIEW

**Comment by abychko** [comment]
Cannot find system lz4 libraries, fixing

**Review by laurynas-biveinis — APPROVED** [review]
OK but I will need to review a full test run once it completes

**Comment by abychko** [comment]
it may take some time. seems we need to build some custom packages and ship them

**Comment by laurynas-biveinis** [comment]
Can you make a list what packages are missing where?

**Comment by abychko** [comment]
added to commit. we need to build protobuf custom packages, please see  BLD-1228

**Comment by abychko** [comment]
@laurynas-biveinis 

final config is libicu, protobuf, rapidjson = bundled.

centos 6: https://ps2.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/52/consoleFull
centos 7: https://ps2.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/53/consoleFull
xenial: https://ps2.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/54/consoleFull
bionic: https://ps2.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/55/consoleFull
stretch: https://ps2.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/56/consoleFull

**Pull request closed without merging**
