### PR TITLE
JEN-1090 use -DWITH_LIBEVENT=bundled as a build option

### PR DESCRIPTION
**Pull request by hors**
https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-param/51/

Or I can do it only for ubuntu:xenial, debian:stretch and for centos 6/7 OSs.

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
@hors let's use the system one where its version is OK

**Comment by EvgeniyPatlan** [comment]
@laurynas-biveinis it is hard to get libevent-2.1 version installed on all systems. So it is better to use bundled in this case.

**Comment by laurynas-biveinis** [comment]
I meant use system libevent on those systems where it is >= 2.1 out of the box

**Comment by hors** [comment]
https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-param/54/

**Review by EvgeniyPatlan — APPROVED** [review]

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
