### PR TITLE
JEN-1078 decrease value for '--testcase-timeout' option

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Needs a test run: it's a bigger change here than on 8.0 (there: 60 -> 30; here: 450 -> 30)

**Comment by hors** [comment]
> Needs a test run: it's a bigger change here than on 8.0 (there: 60 -> 30; here: 450 -> 30)

https://ps3.cd.percona.com/view/5.7/job/percona-server-5.7-param/

**Comment by laurynas-biveinis** [comment]
@hors job # ?

**Comment by hors** [comment]
> @hors job # ?

All of them were built using new code but e.g. you can check this one: https://ps3.cd.percona.com/view/5.7/job/percona-server-5.7-pipeline/1476/

**Comment by laurynas-biveinis** [comment]
> > @hors job # ?
> 
> All of them were built using new code but e.g. you can check this one: https://ps3.cd.percona.com/view/5.7/job/percona-server-5.7-pipeline/1476/

Same comment as for the 5.6 PR

**Comment by hors** [comment]
> > > @hors job # ?
> > 
> > 
> > All of them were built using new code but e.g. you can check this one: https://ps3.cd.percona.com/view/5.7/job/percona-server-5.7-pipeline/1476/
> 
> Same comment as for the 5.6 PR

correct link is: https://ps3.cd.percona.com/view/5.7/job/percona-server-5.7-param/13/

**Comment by laurynas-biveinis** [comment]
Looks good, thank you

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
