### PR TITLE
JEN-1069 create '/bin/python' symlink for RHEL8

### PR DESCRIPTION
**Pull request by hors**
https://ps3.cd.percona.com/view/5.7/job/percona-server-5.7-pipeline/1397/consoleFull - ok

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Such fix means that our Python scripts are not runnable out of the box on RHEL8

**Comment by hors** [comment]
> Such fix means that our Python scripts are not runnable out of the box on RHEL8

It is just a temporary fix for our tests till scrips are fixed. Using python2 scripts work fine. When I tried  to use python3 I had a lot of errors:
https://ps3.cd.percona.com/view/5.7/job/percona-server-5.7-pipeline/1422/consoleFull

According to the following information https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/ rhel8 will have python3 installed by default so it is more preferable to use python3 for ours scripts.

**Comment by laurynas-biveinis** [comment]
Such temporary fixes have a tendency to stay permanent and we cannot say that our product supports RHEL8 anyway, while they are present, because nobody else can repeat the build/test without hacking their system first.

**Comment by hors** [comment]
> Such temporary fixes have a tendency to stay permanent and we cannot say that our product supports RHEL8 anyway, while they are present, because nobody else can repeat the build/test without hacking their system first.

Ok, thank you for explanation. I am closing this review in such a case.

**Pull request closed without merging**
