### PR TITLE
JEN-1078 decrease value for '--testcase-timeout' option

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Needs a test run: it's a bigger change here than on 8.0 (there: 60 -> 30; here: 450 -> 30)

**Comment by hors** [comment]
> Needs a test run: it's a bigger change here than on 8.0 (there: 60 -> 30; here: 450 -> 30)

https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/

**Comment by laurynas-biveinis** [comment]
@hors job # ?

**Comment by hors** [comment]
> @hors job # ?

All of them were built using new code but e.g. you can check this one: 
https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-pipeline/1158/

**Comment by laurynas-biveinis** [comment]
> > @hors job # ?
> 
> All of them were built using new code but e.g. you can check this one:
> https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-pipeline/1158/

"All" must mean something else, because it cannot be that  https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/5/, https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/3/, https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/2/, https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/1/ are all test jobs for this task

**Comment by hors** [comment]
> > > @hors job # ?
> > 
> > 
> > All of them were built using new code but e.g. you can check this one:
> > https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-pipeline/1158/
> 
> "All" must mean something else, because it cannot be that https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/5/, https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/3/, https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/2/, https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/1/ are all test jobs for this task

Sorry you are right, I did not copy the number in my first comment.
https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-param/5/

**Comment by laurynas-biveinis** [comment]
Looks good, thank you

**Review by laurynas-biveinis — APPROVED** [review]

**Comment by laurynas-biveinis** [comment]
Please do not revert, change the values instead

**Comment by hors** [comment]
> Please do not revert, change the values instead

I saw your comment in the task. I will re-work it.

**Pull request merged**
