### PR TITLE
#23 use debian:jessie for asan

### PR DESCRIPTION
**Pull request by delgod**
Fix https://github.com/Percona-Lab/ps-build/issues/23 for 5.5 5.6

### CODE REVIEW

**Comment by delgod** [comment]
@laurynas-biveinis, could you analyze logs on Jessie with asan

5.7
build- https://s3.us-east-2.amazonaws.com/ps-build-cache/jenkins-percona-server-5.7-pipeline-1378/build.log.gz
mtr - https://s3.us-east-2.amazonaws.com/ps-build-cache/jenkins-percona-server-5.7-pipeline-1378/mtr.output.gz

5.6 
build - https://s3.us-east-2.amazonaws.com/ps-build-cache/jenkins-percona-server-5.6-pipeline-742/build.log.gz
mtr - https://s3.us-east-2.amazonaws.com/ps-build-cache/jenkins-percona-server-5.6-pipeline-742/mtr.output.gz

5.5
build - https://s3.us-east-2.amazonaws.com/ps-build-cache/jenkins-percona-server-5.5-pipeline-877/build.log.gz
mtr - https://s3.us-east-2.amazonaws.com/ps-build-cache/jenkins-percona-server-5.5-pipeline-877/mtr.output.gz

**Comment by laurynas-biveinis** [comment]
@delgod, all build logs look good, and it seems that a switch from Xenial to Jessie fixes the problem.

There is a slight issue that we in general prefer the most recent tools (ASan is being actively developed) to catch more errors - i.e. I'd try to switch not to Jessie but to Bionic or Artful

**Comment by delgod** [comment]
looks like it is disabled on jessie

**Comment by laurynas-biveinis** [comment]
@delgod, do you mean Jessie runs above were not in fact ASan?

**Comment by delgod** [comment]
@laurynas-biveinis I found in Jessie logs 
```
-- Performing Test HAVE_SANITIZE_SCOPE
-- Performing Test HAVE_SANITIZE_SCOPE - Failed
```
I think ASAN doesn't work at all on Jessie.
on other platforms, it is impossible to compile MySQL with ASAN at all
for example bionic - https://ps.cd.percona.com/view/5.5/job/percona-server-5.5-pipeline/897/console

**Comment by laurynas-biveinis** [comment]
@delgod, the build logs above are indeed ASan. The failing test is for -fsanitize-address-use-after-scope, whose presence depends on ASan version. 5.5 and 5.6 do not test for this option, and Jessie would work for them OK. But 5.7 is a problem.

@delgod, could this be because of Docker, maybe some missing capabilities? Again old Jenkins ASan worked in Xenial OK

**Comment by delgod** [comment]
@laurynas-biveinis what do you think, should I merge this PR?

about docker capabilities - I disabled capabilities filtering at all - https://github.com/Percona-Lab/ps-build/commit/c0391724c331589e68d14fc39484b20a5c24eed1
so, now docker similar to chroot

**Comment by laurynas-biveinis** [comment]
Yes let's merge it, it's an improvement for 5.5 and 5.6

**Pull request merged**
