### PR TITLE
JEN-936

### PR DESCRIPTION
**Pull request by abychko**
Percona server build failures at git clean
[+] added chown on ps source dir

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Same review as for the 8.0 version

**Comment by abychko** [comment]
PR is valid

**Review by laurynas-biveinis — APPROVED** [review]
OK if @delgod agrees with the general approach and if testing evidence is provided

**Comment by laurynas-biveinis** [comment]
Should this be closed?

**Pull request closed without merging**
