### PR TITLE
#19 remove PERCONAFT_*/TOKUBACKUP_ options

### PR DESCRIPTION
**Pull request by delgod**
Fixes: #19

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Do any uses of these options need to be removed as well?

**Comment by delgod** [comment]
@laurynas-biveinis, fixed in https://github.com/Percona-Lab/ps-build/pull/25/commits/4936e4e75c4754db1f5c5396b9270decac16c176
please review again

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
Looks better, please remove any git submodule-related code from 5.5 too

**Comment by delgod** [comment]
hm, but these changes only for 5.5, could you elaborate more on this?

**Comment by laurynas-biveinis** [comment]
just remove everything about git submodule :)

**Comment by delgod** [comment]
done, please review again

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
