### PR TITLE
JEN-892 5.7

### PR DESCRIPTION
**Pull request by abychko**

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Needs testing evidence and @georgelorchpercona review

**Comment by abychko** [comment]
@delgod please add @georgelorchpercona to the Percona-Lab

**Comment by abychko** [comment]
started https://ps.cd.percona.com/view/TEST/job/test-percona-server-5.7-pipeline/1/ to test

**Comment by abychko** [comment]
@georgelorchpercona please see https://ps.cd.percona.com/view/TEST/job/test-percona-server-5.7-pipeline/3/console

`mysql-test-run: *** ERROR: Could not find 'ROCKSDB_ENGINES_MTR_ARGS' in 'engines/iuds,engines/funcs' suite(s)`

how to test my changes properly?

**Comment by george-lorch** [comment]
It looks like the you are not de-referencing the variable ${ROCKSDB_ENGINES_MTR_ARGS}

To test you can use some kind of trivial mtr option for the MTR_ARGS and the ROCKSDB_ENGINES_MTR_ARGS with a different value, like maybe MTR_ARGS=--port-base=10000 and ROCKSDB_ENGINES_MTR_ARGS=--port-base=10001 then validate in the result that the right setting is used for the right mtr invocation.

**Comment by abychko** [comment]
https://ps.cd.percona.com/view/TEST/job/test-percona-server-5.7-pipeline/4/console 
seems it looks correct? @georgelorchpercona please take a look

**Review by george-lorch — APPROVED** [review]
Yup, this looks good.

**Comment by abychko** [comment]
@laurynas-biveinis ?

**Comment by laurynas-biveinis** [comment]
This does not need my review since George reviewed it

**Review by delgod — APPROVED** [review]

**Pull request closed without merging**
