### PR TITLE
Jen 926 8.0

### PR DESCRIPTION
**Pull request by abychko**

### CODE REVIEW

**Comment by abychko** [comment]
https://ps.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/18/

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
The awk invocation is repeated three times and is not trivial. Can it be extracted to shell something in order to avoid two copy-pastes?

**Comment by abychko** [comment]
yes, it can be extracted, but please make it separate task. need to fight variables dereferension in single/double quotes

**Comment by laurynas-biveinis** [comment]
OK, can you please file a JEN issue yourself?

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
