### PR TITLE
JEN-957 add additional trunk jobs

### PR DESCRIPTION
**Pull request by hors**
* add 'percona-server-8.0-trunk-max-parts' and
      'percona-server-8.0-trunk-special' jobs

### CODE REVIEW

**Comment by hors** [comment]
@laurynas-biveinis  I have additional question for you.  Should we run these jobs for all supported OSs?

**Comment by hors** [comment]
https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-trunk-special/2/
https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-trunk-max-parts/1/

**Comment by laurynas-biveinis** [comment]
@hors all OSes, yes

**Comment by hors** [comment]
> @hors all OSes, yes

ok, please review

**Review by laurynas-biveinis — COMMENTED** [review]
Can they use not the cron schedule (which also then would need some consideration so that all trunk jobs don't hit at the same time), but be dependant job on the main trunk job, triggering after it completes?

**Comment by hors** [comment]
> Can they use not the cron schedule (which also then would need some consideration so that all trunk jobs don't hit at the same time), but be dependant job on the main trunk job, triggering after it completes?

yes, I can do it but as I understand these jobs do not depend on trunk job and we can run them in a parallel. That is why I scheduled one job for 1 am and the second one for 3 am (the first one had to be finished till this time). If we trigger these jobs as soon as main trunk job is finished, we will have loaded jenkins at our working hours because as you know main trunk job finishes approximately at 9 am UTC.

**Comment by laurynas-biveinis** [comment]
It's not easy avoid working hours work, I am not sure how 2h later start helps, since the trunk jobs are much longer:

https://ps80.cd.percona.com/job/percona-server-8.0-trunk/29/ "Took 13h"
https://ps80.cd.percona.com/job/percona-server-8.0-trunk/30/ - aborted after 9h (by you, why?)
https://ps80.cd.percona.com/job/percona-server-8.0-trunk/31/ - aborted after 7h
https://ps80.cd.percona.com/job/percona-server-8.0-trunk/32/ - 3h indeed but only one worker run, others are skipped - why?

**Comment by hors** [comment]
> It's not easy avoid working hours work, I am not sure how 2h later start helps, since the trunk jobs are much longer:
> 
> https://ps80.cd.percona.com/job/percona-server-8.0-trunk/29/ "Took 13h"
> https://ps80.cd.percona.com/job/percona-server-8.0-trunk/30/ - aborted after 9h (by you, why?)
> https://ps80.cd.percona.com/job/percona-server-8.0-trunk/31/ - aborted after 7h
> https://ps80.cd.percona.com/job/percona-server-8.0-trunk/32/ - 3h indeed but only one worker run, others are skipped - why?

These jobs hung yesterday, I have investigated  this issue. the root of the issue is the same as we are discussing in https://jira.percona.com/browse/JEN-1078 . I have killed them and restarted. After the second run two jobs hung and I restarted them the second time.

**Comment by hors** [comment]
If everything  is ok, it should not take more than 9-10 hours. It is good example https://ps80.cd.percona.com/job/percona-server-8.0-trunk/26/

Now at night we have lower load of our jenkins but if you want to run them after trunk job is completed I can do it. But I do not suggest starting them at the same time. We can start the first one and as soon as it finishes trigger the second one. What do you think?

**Comment by laurynas-biveinis** [comment]
That looks like my original suggestion, with job completion triggering the next job and that's how it was in the old Jenkins. Works for me

**Comment by laurynas-biveinis** [comment]
@hors can you provide new test job links?

**Comment by hors** [comment]
> @hors can you provide new test job links?

https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-trunk-max-parts/2/
https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-trunk-special/3/

**Comment by laurynas-biveinis** [comment]
For max-parts, test timeout needs a bump
For special,
```
190506 23:39:09 [ 33%] special.innodb_dedicated_server           [ fail ]
        Test ended at 2019-05-06 23:39:09

CURRENT_TEST: special.innodb_dedicated_server
Can't locate Sys/MemInfo.pm in @INC (@INC contains: /opt/rh/devtoolset-7/root//usr/lib64/perl5/vendor_perl /opt/rh/devtoolset-7/root/usr/lib/perl5 /opt/rh/devtoolset-7/root//usr/share/perl5/vendor_perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /tmp/results/PS/mysql-test/var/tmpZNWXpc line 2.
```

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
As commented

**Comment by hors** [comment]
Thank you for your comments and time, the max-parts job was fixed:
https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-trunk-max-parts/6/
but almost all tests in special job failed:
https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-trunk-special/5/
please have a look at the log and inform me if any additional changes are needed from my end.

**Review by laurynas-biveinis — APPROVED** [review]
Looks good, thank you. The "special" suite failures look like test not Jenkins bug, I will handle them

**Comment by hors** [comment]
> Looks good, thank you. The "special" suite failures look like test not Jenkins bug, I will handle them

ok, thank you

**Comment by laurynas-biveinis** [comment]
@hors let's disable "special" suite until https://bugs.mysql.com/bug.php?id=95344 is fixed

**Comment by hors** [comment]
> @hors let's disable "special" suite until https://bugs.mysql.com/bug.php?id=95344 is fixed

ok

**Pull request merged**
