### PR TITLE
JEN-959

### PR DESCRIPTION
**Pull request by abychko**
8.0 Add --non-parallel-test to the default MTR arg list

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Will the MTR_ARGS refactoring happen in another PR?

**Comment by abychko** [comment]
yes, better to merge minor changes before

**Review by laurynas-biveinis — APPROVED** [review]
OK if testing OK

**Comment by abychko** [comment]
started test https://ps2.cd.percona.com/view/TEST/job/test-percona-server-8.0-pipeline/5/

**Comment by laurynas-biveinis** [comment]
@abychko please use 3637583bb5217f8e2a287870775fd5657de271bc, not HEAD, for any 8.0-testing jobs

**Comment by abychko** [comment]
upstream mysql test run: https://ps2.cd.percona.com/view/TEST/job/test-percona-server-8.0-pipeline/8/consoleFull

**Review by laurynas-biveinis — APPROVED** [review]

**Pull request merged**
