### PR TITLE
JEN-936

### PR DESCRIPTION
**Pull request by abychko**
Percona server build failures at git clean
[+] added chown on ps source dir

### CODE REVIEW

**Review by laurynas-biveinis — COMMENTED** [review]
Please show testing evidence for @dutow
Why git reset and git clean changed places?

**Comment by abychko** [comment]
re: testing evidence. I don't know how to reproduce build on reused VM or docker image to have broken permissions in the source tree. I can ran builds as usual, but they can't give us any proof.

re: git. it's better to clean before reset because some files may exist or not exist in different branches or revisions.

**Comment by laurynas-biveinis** [comment]
> re: testing evidence. I don't know how to reproduce build on reused VM or docker image to have broken permissions in the source tree. I can ran builds as usual, but they can't give us any proof.

ack, please discuss with @inikep on Slack/JIRA

> re: git. it's better to clean before reset because some files may exist or not exist in different branches or revisions.

This is exactly why I think reset first is better - in the case of branch change it will determine which files should be removed by a later clean. In any case, is it directly related to permission fix? If not, please PR separately

**Comment by dutow** [comment]
@abychko Looking at the build history for this morning, first I started a build, then aborted it as I forgot to push an update - maybe that could be the cause?
After that, I tried starting a new build several times, but it always failed within minutes. Now that a few hours passed, it works again.

**Comment by abychko** [comment]
Yes, the reason is reusing of dirty image. I believe we should fix it anyway

**Comment by abychko** [comment]
changed back order of git clean & reset

**Comment by abychko** [comment]
> > re: testing evidence. I don't know how to reproduce build on reused VM or docker image to have broken permissions in the source tree. I can ran builds as usual, but they can't give us any proof.
> 
> ack, please discuss with @inikep on Slack/JIRA

sorry, discuss what? build on dirty images?

**Comment by laurynas-biveinis** [comment]
> sorry, discuss what? build on dirty images?

It seems you already have discussed above

**Comment by laurynas-biveinis** [comment]
ad0edf1 does not do what it says it should. And since this is a non-trunk branch, a better practice is to remove commit and push with --force-with-lease rather than add reverting commit on the top

**Comment by abychko** [comment]
I can squash and merge commits as one commit

**Comment by abychko** [comment]
done according to your comments

**Comment by delgod** [comment]
btw I think it is better to run `sudo chown` before `local/checkout` script in pipeline https://github.com/Percona-Lab/ps-build/blob/5.7/jenkins/pipeline.groovy#L157
not inside `local/checkout` script which can run without root on developer machine.

**Comment by abychko** [comment]
ok, makes sense

**Comment by abychko** [comment]
issue is reproducible locally, without Jenkins. so, chown call should be in script, not in pipeline

**Review by laurynas-biveinis — APPROVED** [review]
OK if @delgod agrees with the general approach and if testing evidence is provided

**Comment by laurynas-biveinis** [comment]
Should this be closed?

**Comment by abychko** [comment]
closed or merged & closed?

**Comment by laurynas-biveinis** [comment]
I don't know. It's opened for six weeks now

**Pull request closed without merging**
