### PR TITLE
JEN-964

### PR DESCRIPTION
**Pull request by abychko**
percona-server-5.7-valgrind-param has only `default` configuration
[+] added additional platforms to the job

### CODE REVIEW

**Review by laurynas-biveinis — CHANGES_REQUESTED** [review]
The list should be identical to the one in https://github.com/Percona-Lab/ps-build/blob/4f7acf9d5e8790d1c58c7904ccc1f943ef2e3f14/jenkins/param.yml ? 

Is it possible to have some .yml include file shared between them?

Please also provide testing evidence

**Comment by abychko** [comment]
copied all platforms from param job

**Comment by abychko** [comment]
test run https://ps2.cd.percona.com/job/percona-server-5.7-valgrind-param/1/

**Comment by abychko** [comment]
test run seems OK, but test result junit is unreadable due to changed output format

**Comment by laurynas-biveinis** [comment]
But there is a red dot:
https://ps2.cd.percona.com/job/percona-server-5.7-pipeline/73/consoleText
-- Looking for include files valgrind/memcheck.h, valgrind/valgrind.h
-- Looking for include files valgrind/memcheck.h, valgrind/valgrind.h - not found
CMake Error at configure.cmake:662 (MESSAGE):
  Unable to find Valgrind header files
  valgrind/memcheck.h;valgrind/valgrind.h.  Make sure you have them in your
  include path.

**Review by laurynas-biveinis — APPROVED** [review]
The change looks good - please merge, and then then fix the red-dot slave, and then close JEN-964

**Pull request merged**
