### PR TITLE
PS-8854: Adjust scripts to work with PS 8.1

### PR DESCRIPTION
**Pull request by oleksandr-kachan**
https://jira.percona.com/browse/PS-8854

- change '8.0' branch name to '8.x' everywhere in names or remove it depending on context
- rename keyring_vault test suite to component_keyring_vault
- rename audit_log_filter test suite to component_audit_log_filter
- add percona and percona_innodb suits to suites-groups.sh
- remove WITH_KEYRING_VAULT parameter, always build component
- remove parametrs declaration in pipeline-parallel-mtr.yml, they are declared in corresponding groovy file

### CODE REVIEW

**Review by percona-ysorokin — CHANGES_REQUESTED** [review]
Please include "percona" and "percona_innodb" test suites in one of the worker1..worker8 suite list

**Comment by oleksandr-kachan** [comment]
> Please include "percona" and "percona_innodb" test suites in one of the worker1..worker8 suite list

Done

**Review by EvgeniyPatlan — APPROVED** [review]

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Review by vorsel — APPROVED** [review]

**Comment by inikep** [comment]
We also added `component_encryption_udf` suite in 8.1.

**Comment by oleksandr-kachan** [comment]
> We also added `component_encryption_udf` suite in 8.1.

Thanks, will recheck and add it separately

**Pull request merged**
